// js/library.js
// simple global object used when data/library.json is not present
var LIBRARY = {
  Art: [
    {
      id: "art-1",
      title: "Cocreating the Future - Inclusion in and through Design",
      author: "",
      file: "Art/Cocreating the Future - Inclusion in and through Design.pdf",
    },
    {
      id: "art-2",
      title: "William J Mitchell - City of Bits",
      author: "William J Mitchell",
      file: "Art/William J Mitchell - City of Bits.pdf",
    },
  ],
  Business: [
    {
      id: "bus-1",
      title: "Ashlee Vance - Elon Musk",
      author: "Ashlee Vance",
      file: "Business/Ashlee Vance - Elon Musk.pdf",
    },
    {
      id: "bus-2",
      title: "Benjamin Graham - The Intelligent Investor",
      author: "Benjamin Graham",
      file: "Business/Benjamin Graham - The Intelligent Investor.pdf",
    },
    {
      id: "bus-3",
      title: "Dan Sisson - Google SEO Secrets",
      author: "Dan Sisson",
      file: "Business/Dan Sisson - Google SEO Secrets.pdf",
    },
    {
      id: "bus-4",
      title: "Erin Meyer - No Rules Rule",
      author: "Erin Meyer",
      file: "Business/Erin Meyer - No Rules Rule.pdf",
    },
    {
      id: "bus-5",
      title: "Erin Meyer - The Culture Map",
      author: "Erin Meyer",
      file: "Business/Erin Meyer - The Culture Map.pdf",
    },
    {
      id: "bus-6",
      title: "Frederick Betz - Managing Technological Innovation",
      author: "Frederick Betz",
      file: "Business/Frederick Betz - Managing Technological Innovation.pdf",
    },
    {
      id: "bus-7",
      title: "Gregory Zuckerman - The Man Who Solved the Market",
      author: "Gregory Zuckerman",
      file: "Business/Gregory Zuckerman - The Man Who Solved the Market.pdf",
    },
    {
      id: "bus-8",
      title: "Philip Kotler - Chaotics",
      author: "Philip Kotler",
      file: "Business/Philip Kotler - Chaotics.pdf",
    },
    {
      id: "bus-9",
      title: "Simon Sinek - Leaders Eat Last",
      author: "Simon Sinek",
      file: "Business/Simon Sinek - Leaders Eat Last.pdf",
    },
    {
      id: "bus-10",
      title: "Thiago Nigro - Do Mil Ao Milhao",
      author: "Thiago Nigro",
      file: "Business/Thiago Nigro - Do Mil Ao Milhao.pdf",
    },
  ],
  Literature: [
    {
      id: "lit-1",
      title: "Albert Camus - Yabancı",
      author: "Albert Camus",
      file: "Literature/Albert Camus - Yabancı.pdf",
    },
    {
      id: "lit-2",
      title: "Cengiz Aytmatov - Cengiz Hana Küsen Bulut",
      author: "Cengiz Aytmatov",
      file: "Literature/Cengiz Aytmatov - Cengiz Hana Küsen Bulut.pdf",
    },
    {
      id: "lit-3",
      title: "George Orwell - 1984",
      author: "George Orwell",
      file: "Literature/George Orwell - 1984.pdf",
    },
    {
      id: "lit-4",
      title: "George Orwell - Animal Farm",
      author: "George Orwell",
      file: "Literature/George Orwell - Animal Farm.pdf",
    },
    {
      id: "lit-5",
      title: "Paulo Coelho - Simyacı",
      author: "Paulo Coelho",
      file: "Literature/Paulo Coelho - Simyacı.pdf",
    },
    {
      id: "lit-6",
      title: "Sabahattin Ali - Kürk Mantolu Madonna",
      author: "Sabahattin Ali",
      file: "Literature/Sabahattin Ali - Kürk Mantolu Madonna.pdf",
    },
    {
      id: "lit-7",
      title: "Sabahattin Ali - İçimizdeki Şeytan",
      author: "Sabahattin Ali",
      file: "Literature/Sabahattin Ali - İçimizdeki Şeytan.pdf",
    },
    {
      id: "lit-8",
      title: "Stefan Zweig - Satranç",
      author: "Stefan Zweig",
      file: "Literature/Stefan Zweig - Satranç.pdf",
    },
    {
      id: "lit-9",
      title: "Tarık Buğra - Küçük Ağa",
      author: "Tarık Buğra",
      file: "Literature/Tarık Buğra - Küçük Ağa.pdf",
    },
    {
      id: "lit-10",
      title: "William Shakespeare - Hamlet",
      author: "William Shakespeare",
      file: "Literature/William Shakespeare - Hamlet.pdf",
    },
  ],
  "Must-Read": [
    {
      id: "mr-1",
      title: "Cal Newport - Deep Work",
      author: "Cal Newport",
      file: "Must-Read/Cal Newport - Deep Work.epub",
    },
    {
      id: "mr-2",
      title: "Carol Dweck - Mindset",
      author: "Carol Dweck",
      file: "Must-Read/Carol Dweck - Mindset.epub",
    },
    {
      id: "mr-3",
      title: "Dale Carnegie - How To Stop Worrying And Start Living",
      author: "Dale Carnegie",
      file: "Must-Read/Dale Carnegie - How To Stop Worrying And Start Living.epub",
    },
    {
      id: "mr-4",
      title: "Daron Acemoğlu - Ulusların Düşüşü",
      author: "Daron Acemoğlu",
      file: "Must-Read/Daron Acemoğlu - Ulusların Düşüşü.epub",
    },
    {
      id: "mr-5",
      title: "David Allen - Getting Things Done",
      author: "David Allen",
      file: "Must-Read/David Allen - Getting Things Done.epub",
    },
    {
      id: "mr-6",
      title: "Gary Chapman - The 5 Love Languages",
      author: "Gary Chapman",
      file: "Must-Read/Gary Chapman - The 5 Love Languages.epub",
    },
    {
      id: "mr-7",
      title: "Gary Keller - The One Thing",
      author: "Gary Keller",
      file: "Must-Read/Gary Keller - The One Thing.epub",
    },
    {
      id: "mr-8",
      title: "Grant Cardone - The 10x Rule",
      author: "Grant Cardone",
      file: "Must-Read/Grant Cardone - The 10x Rule.epub",
    },
    {
      id: "mr-9",
      title: "Gretchen Rubin - The Happiness Project",
      author: "Gretchen Rubin",
      file: "Must-Read/Gretchen Rubin - The Happiness Project.epub",
    },
    {
      id: "mr-10",
      title: "Hector Garcia - Ikigai",
      author: "Hector Garcia",
      file: "Must-Read/Hector Garcia - Ikigai.epub",
    },
    {
      id: "mr-11",
      title: "Ian Robertson - The Winner Effect",
      author: "Ian Robertson",
      file: "Must-Read/Ian Robertson - The Winner Effect.epub",
    },
    {
      id: "mr-12",
      title: "Jackson MacKenzie - Psychopath Free",
      author: "Jackson MacKenzie",
      file: "Must-Read/Jackson MacKenzie - Psychopath Free.epub",
    },
    {
      id: "mr-13",
      title: "James Clear - Atomic Habits",
      author: "James Clear",
      file: "Must-Read/James Clear - Atomic Habits.epub",
    },
    {
      id: "mr-14",
      title: "James Collins - Good to Great",
      author: "James Collins",
      file: "Must-Read/James Collins - Good to Great.epub",
    },
    {
      id: "mr-15",
      title: "Jancee Dunn - How Not to Hate Your Husband After Kids",
      author: "Jancee Dunn",
      file: "Must-Read/Jancee Dunn - How Not to Hate Your Husband After Kids.epub",
    },
    {
      id: "mr-16",
      title: "Jordan Peterson - 12 Rules for Life",
      author: "Jordan Peterson",
      file: "Must-Read/Jordan Peterson - 12 Rules for Life.epub",
    },
    {
      id: "mr-17",
      title: "Joseph Shaules - The Intercultural Mind",
      author: "Joseph Shaules",
      file: "Must-Read/Joseph Shaules - The Intercultural Mind.epub",
    },
    {
      id: "mr-18",
      title: "Katty Kay - The Confidence Code",
      author: "Katty Kay",
      file: "Must-Read/Katty Kay - The Confidence Code.epub",
    },
    {
      id: "mr-19",
      title: "Keith Ferrazzi - Never Eat Alone",
      author: "Keith Ferrazzi",
      file: "Must-Read/Keith Ferrazzi - Never Eat Alone.epub",
    },
    {
      id: "mr-20",
      title: "Laura Vanderkam - 168 Hours",
      author: "Laura Vanderkam",
      file: "Must-Read/Laura Vanderkam - 168 Hours.epub",
    },
    {
      id: "mr-21",
      title: "Leil Lowndes - How to Talk to Anyone",
      author: "Leil Lowndes",
      file: "Must-Read/Leil Lowndes - How to Talk to Anyone.epub",
    },
    {
      id: "mr-22",
      title: "Malcolm Gladwell - Talking to Strangers",
      author: "Malcolm Gladwell",
      file: "Must-Read/Malcolm Gladwell - Talking to Strangers.epub",
    },
    {
      id: "mr-23",
      title: "Morgan Housel - Same as Ever",
      author: "Morgan Housel",
      file: "Must-Read/Morgan Housel - Same as Ever.epub",
    },
    {
      id: "mr-24",
      title: "Morten Hansen - Great at Work",
      author: "Morten Hansen",
      file: "Must-Read/Morten Hansen - Great at Work.epub",
    },
    {
      id: "mr-25",
      title: "Napoleon Hill - Think and Grow Rich",
      author: "Napoleon Hill",
      file: "Must-Read/Napoleon Hill - Think and Grow Rich.epub",
    },
    {
      id: "mr-26",
      title: "Richard Koch - The 80-20 Principle",
      author: "Richard Koch",
      file: "Must-Read/Richard Koch - The 80-20 Principle.epub",
    },
    {
      id: "mr-27",
      title: "Robert Kiyosaki - Rich Dad Poor Dad",
      author: "Robert Kiyosaki",
      file: "Must-Read/Robert Kiyosaki - Rich Dad Poor Dad.epub",
    },
    {
      id: "mr-28",
      title: "Robin Sharma - The 5 AM Club",
      author: "Robin Sharma",
      file: "Must-Read/Robin Sharma - The 5 AM Club.epub",
    },
    {
      id: "mr-29",
      title: "Scott Gerber - Never Get a Real Job",
      author: "Scott Gerber",
      file: "Must-Read/Scott Gerber - Never Get a Real Job.epub",
    },
    {
      id: "mr-30",
      title: "Stephen Covey - The 7 Habits of Highly Effective People",
      author: "Stephen Covey",
      file: "Must-Read/Stephen Covey - The 7 Habits of Highly Effective People.epub",
    },
    {
      id: "mr-31",
      title: "Susan Cain - Quiet",
      author: "Susan Cain",
      file: "Must-Read/Susan Cain - Quiet.epub",
    },
    {
      id: "mr-32",
      title: "William Irvine - A Guide to the Good Life",
      author: "William Irvine",
      file: "Must-Read/William Irvine - A Guide to the Good Life.epub",
    },
    {
      id: "mr-33",
      title: "William McRaven - Make Your Bed",
      author: "William McRaven",
      file: "Must-Read/William McRaven - Make Your Bed.epub",
    },
  ],
  "Self-Development": [
    {
      id: "sd-1",
      title: "Charles Henderson - You Can Do It with Self-Hypnosis",
      author: "Charles Henderson",
      file: "Self-Development/Charles Henderson - You Can Do It with Self-Hypnosis.pdf",
    },
    {
      id: "sd-2",
      title: "Jack Canfield - The Success Principles",
      author: "Jack Canfield",
      file: "Self-Development/Jack Canfield - The Success Principles.pdf",
    },
    {
      id: "sd-3",
      title: "Kim Scott - Radical Candor",
      author: "Kim Scott",
      file: "Self-Development/Kim Scott - Radical Candor.pdf",
    },
    {
      id: "sd-4",
      title: "Malcolm Gladwell - Outliers",
      author: "Malcolm Gladwell",
      file: "Self-Development/Malcolm Gladwell - Outliers.pdf",
    },
    {
      id: "sd-5",
      title: "Napoleon Hill - Outwitting the Devil",
      author: "Napoleon Hill",
      file: "Self-Development/Napoleon Hill - Outwitting the Devil.pdf",
    },
    {
      id: "sd-6",
      title: "Robert Cialdini - The Psychology of Persuasion",
      author: "Robert Cialdini",
      file: "Self-Development/Robert Cialdini - The Psychology of Persuasion.pdf",
    },
    {
      id: "sd-7",
      title: "Üstün Dökmen - Küçük Şeyler",
      author: "Üstün Dökmen",
      file: "Self-Development/Üstün Dökmen - Küçük Şeyler.PDF",
    },
  ],
  Software: [
    {
      id: "sw-1",
      title: "Charles Petzold - Code",
      author: "Charles Petzold",
      file: "Software/Charles Petzold - Code.pdf",
    },
    {
      id: "sw-2",
      title: "Derek Runberg - The SparkFun Guide to Processing",
      author: "Derek Runberg",
      file: "Software/Derek Runberg - The SparkFun Guide to Processing.pdf",
    },
    {
      id: "sw-3",
      title: "Paul Graham - Hackers and Painters",
      author: "Paul Graham",
      file: "Software/Paul Graham - Hackers and Painters.pdf",
    },
    {
      id: "sw-4",
      title: "Robert Martin - Clean Architecture",
      author: "Robert C. Martin",
      file: "Software/Robert Martin - Clean Architecture.pdf",
    },
    {
      id: "sw-5",
      title: "Robert Martin - Clean Code",
      author: "Robert C. Martin",
      file: "Software/Robert Martin - Clean Code.pdf",
    },
    {
      id: "sw-6",
      title: "Robert Martin - The Clean Coder",
      author: "Robert C. Martin",
      file: "Software/Robert Martin - The Clean Coder.pdf",
    },
  ],
  _Article_: [
    {
      id: "a-1",
      title: "Jennifer Routh - Rating and ranking preparedness",
      author: "Jennifer Routh",
      file: "_Article_/Jennifer Routh - Rating and ranking preparedness.pdf",
    },
    {
      id: "a-2",
      title:
        "Nariman Zadeh - Crowdsourcing Subjective Annotations Using Pairwise Comparisons",
      author: "Nariman Zadeh",
      file: "_Article_/Nariman Zadeh - Crowdsourcing Subjective Annotations Using Pairwise Comparisons.pdf",
    },
    {
      id: "a-3",
      title: "Xi Chen - Pairwise Ranking Aggregation in a Crowdsourced Setting",
      author: "Xi Chen",
      file: "_Article_/Xi Chen - Pairwise Ranking Aggregation in a Crowdsourced Setting.pdf",
    },
  ],
  ComplexExam: [
    {
      id: "ce-cg-1",
      title:
        "Eric Lengyel - Mathematics for 3D Game Programming and Computer Graphics",
      author: "Eric Lengyel",
      file: "ComplexExam/Computer graphics and applied geometry/Eric Lengyel - Mathematics for 3D Game Programming and Computer Graphics.pdf",
    },
    {
      id: "ce-cg-2",
      title: "John Hughes - Computer Graphics Principles and Practice",
      author: "John Hughes",
      file: "ComplexExam/Computer graphics and applied geometry/John Hughes - Computer Graphics Principles and Practice.pdf",
    },
    {
      id: "ce-cg-3",
      title: "North Holland - Handbook of Computer Aided Geometric Design",
      author: "Various",
      file: "ComplexExam/Computer graphics and applied geometry/North Holland - Handbook of Computer Aided Geometric Design.pdf",
    },
    {
      id: "ce-cg-4",
      title: "Peter Shirley - Fundamentals of Computer Graphics",
      author: "Peter Shirley",
      file: "ComplexExam/Computer graphics and applied geometry/Peter Shirley - Fundamentals of Computer Graphics.pdf",
    },
    {
      id: "ce-vr-1",
      title: "Jason Jerald - The VR Book",
      author: "Jason Jerald",
      file: "ComplexExam/Virtual and augmented reality/Jason Jerald - The VR Book.pdf",
    },
    {
      id: "ce-vr-2",
      title: "Steven LaValle - Virtual Reality",
      author: "Steven LaValle",
      file: "ComplexExam/Virtual and augmented reality/Steven LaValle - Virtual Reality.pdf",
    },
    {
      id: "ce-vr-3",
      title: "Tony Parisi - Learning Virtual Reality",
      author: "Tony Parisi",
      file: "ComplexExam/Virtual and augmented reality/Tony Parisi - Learning Virtual Reality.pdf",
    },
    {
      id: "ce-vr-4",
      title: "William Sherman - Understanding Virtual Reality",
      author: "William Sherman",
      file: "ComplexExam/Virtual and augmented reality/William Sherman - Understanding Virtual Reality.pdf",
    },
  ],
};
